### ISSUE TITLE
Disable editing of entity variables known to break the game

### ISSUE THREAD

**Issue by ghost** [matthewrkarlsen/open-diablo-editor#11]
At present the editor is a "power tool" for those who know what they are doing in great depth. Whilst the tool should remain accessible to power users, we also need to make the tool accessible to more casual users and thus we need to remove all 'highly experimental' variables until their function is better understood.

**Comment by matthewrkarlsen** [comment]
Closing this ticket -- development has moved to [the version 2 repo](https://github.com/matthewrkarlsen/open-diablo-editor-2).
