### ISSUE TITLE
Hellfire support

### ISSUE THREAD

**Issue by ghost** [matthewrkarlsen/open-diablo-editor#12]
Support the Hellfire binary, not just the 1.09 Diablo.exe binary. This is likely to take a while to implement because there are other more pressing features and this is a large project in itself (the location offests in the binary are all different for Hellfire).

**Comment by matthewrkarlsen** [comment]
Closing this ticket -- development has moved to [the version 2 repo](https://github.com/matthewrkarlsen/open-diablo-editor-2).
