### ISSUE TITLE
Better save functionality

### ISSUE THREAD

**Issue by ghost** [matthewrkarlsen/open-diablo-editor#6]
Currently pressing the save button on an individual entity writes to the binary file. This should be modified so that "save" is replaced with something along the lines of "Cache modifications". This button would preserve the changes temporarily (so that you can switch between items and it preserves the changes) but would no longer write to disk. A new button should then be created that writes to disk.

**Comment by matthewrkarlsen** [comment]
Closing this ticket -- development has moved to [the version 2 repo](https://github.com/matthewrkarlsen/open-diablo-editor-2).
