### ISSUE TITLE
Fix the hack on line ~425 of BaseMonstersPanel.java

### ISSUE THREAD

**Issue by ghost** [matthewrkarlsen/open-diablo-editor#7]
Currently we have:
```java
if(!maxHitPointsField.getText().equals("")) { //FIXME -- hack. need to fix.
	baseMonster.setMaxHitPoints(Long.parseLong(maxHitPointsField.getText()));
}
```
This is ugly and needs better understanding then fixing.

**Comment by matthewrkarlsen** [comment]
Closing this ticket -- development has moved to [the version 2 repo](https://github.com/matthewrkarlsen/open-diablo-editor-2).
