### ISSUE TITLE
Feature: copy+paste or swap entities

### ISSUE THREAD

**Issue by ghost** [matthewrkarlsen/open-diablo-editor#8]
It would be useful if you could copy one entity over another one (for instance, replace the Zombie entity with a copy of the Devil Kin entity for future editing) or swap the positions of two entities. Some kind of cut/paste entity feature, with an additional swap option, would achieve this.

**Comment by matthewrkarlsen** [comment]
Closing this ticket -- development has moved to [the version 2 repo](https://github.com/matthewrkarlsen/open-diablo-editor-2).
