### ISSUE TITLE
Fix editing of text strings (e.g. item names)

### ISSUE THREAD

**Issue by ghost** [matthewrkarlsen/open-diablo-editor#9]
Due to the complexities involved in directly modifying a binary file, altering the names currently does not work. This needs to be fixed or resolved somehow (possibly by moving around bits of the binary so that space is freed up for more text). **This is a difficult/time consuming issue.**

**Comment by matthewrkarlsen** [comment]
Closing this ticket -- development has moved to [the version 2 repo](https://github.com/matthewrkarlsen/open-diablo-editor-2).
